# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculate_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63\x61lculate_service.proto\x12\x03rpc\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\"\n\nSubRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1d\n\x0bSubResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x66\n\x10\x43\x61lculateService\x12(\n\x03\x41\x64\x64\x12\x0f.rpc.AddRequest\x1a\x10.rpc.AddResponse\x12(\n\x03Sub\x12\x0f.rpc.SubRequest\x1a\x10.rpc.SubResponseB\x03\x80\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculate_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\001'
  _ADDREQUEST._serialized_start=32
  _ADDREQUEST._serialized_end=66
  _ADDRESPONSE._serialized_start=68
  _ADDRESPONSE._serialized_end=97
  _SUBREQUEST._serialized_start=99
  _SUBREQUEST._serialized_end=133
  _SUBRESPONSE._serialized_start=135
  _SUBRESPONSE._serialized_end=164
  _CALCULATESERVICE._serialized_start=166
  _CALCULATESERVICE._serialized_end=268
# @@protoc_insertion_point(module_scope)
