# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65\x63ho_service.proto\x12\x03rpc\"\x1f\n\x0b\x45\x63hoRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\"\x1e\n\x0c\x45\x63hoResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2:\n\x0b\x45\x63hoService\x12+\n\x04\x45\x63ho\x12\x10.rpc.EchoRequest\x1a\x11.rpc.EchoResponseB\x03\x80\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\001'
  _ECHOREQUEST._serialized_start=27
  _ECHOREQUEST._serialized_end=58
  _ECHORESPONSE._serialized_start=60
  _ECHORESPONSE._serialized_end=90
  _ECHOSERVICE._serialized_start=92
  _ECHOSERVICE._serialized_end=150
# @@protoc_insertion_point(module_scope)
